site_name: Omoospace Docs
site_url: https://omoolab.github.io/omoospace/
site_author: OmooLab
site_description: Omoospace is a scalable directory structure solution for digital creation works.

repo_name: omoolab/omoospace
repo_url: https://github.com/omoolab/omoospace

nav:
  - Getting Stared:
      - index.md
      - What is omoospace?: omoospace.md
      - For Artists: artists.md
      - For Developers: developers.md
      - Features Roadmap: roadmap.md
  - API Reference:
      - Omoospace: apis/omoospace.md
      - Subspace: apis/subspace.md
      - Package: apis/package.md

theme:
  name: material
  logo: assets/Logo.png
  language: en
  font:
    text: Noto Sans
    code: Cascadia Code
  palette:
    scheme: default
    primary: black
  features:
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select

extra:
  version:
    provider: mike

copyright: Copyright &copy; 2020 - 2024 Omoolab

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - mkdocs-click
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
